name: flutter_windows_simlutor
description: Flutter Windows Simlutor

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  phlox_animations: ^2.1.1
  loading_indicator: ^3.1.0
  hovering: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - Assets/
    - Assets/Fonts/
    - Assets/Fonts/Shabnam.ttf
    - Assets/Images/

  fonts:
    - family: Shabnam
      fonts:
        - asset: Assets/Fonts/Shabnam.ttf

    - family: Lalezar
      fonts:
        - asset: Assets/Fonts/Lalezar.ttf
